# .travis.yml
language: bash


addons:
  apt:
    packages:
      - build-essential libncurses-dev flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf
      - linux-headers-$(uname -r)

before_install:
  - test -d linux || git clone --depth 1 https://github.com/torvalds/linux linux

install:
  - ( cd linux; git pull )

before_script:
  - rm -rf linux/fs/isofs
  - cp -r fs/isofs linux/fs/
  - cp /boot/config-$(uname -r) linux/.config

script:
  - cd linux
  - git diff
  - yes "" | make modules_prepare
  - make M=fs/isofs